# Test preproc file construction to avoid FITS errors


## Replicate `desi_preproc` script

Example call to `desi_preproc`:
```
desi_preproc -n 20210412 -e 84523 --cameras r0 \
    --fibermap $DESI_ROOT/spectro/redux/f3/preproc/20210412/00084523/fibermap-00084523.fits \
    --outfile preproc-r0-00084523.fits
```
For details see [desihub/desidatamodel#87](https://github.com/desihub/desidatamodel/issues/87).

## Set up options

In [7]:
import os
from desispec.io import findfile, read_raw

In [8]:
night = 20210412
expid = 84523
camera = 'r0'
infile = findfile('raw', night, expid)
fibermap = os.path.join(os.environ['DESI_SPECTRO_REDUX'], os.environ['SPECPROD'], 'preproc', str(night), f'{expid:08d}', f'fibermap-{expid:08d}.fits')
outfile = os.path.join(os.environ['CSCRATCH'], f'preproc-{camera}-{expid:08d}.fits')
infile, fibermap, outfile

('/global/cfs/cdirs/desi/spectro/data/20210412/00084523/desi-00084523.fits.fz',
 '/global/cfs/cdirs/desi/spectro/redux/f3/preproc/20210412/00084523/fibermap-00084523.fits',
 '/global/cscratch1/sd/bweaver/preproc-r0-00084523.fits')

In [10]:
#
# Interesting design choice: even though fill_header=None, it still fills from HDU 0.  It is triggered by the fact that the keyword exists, not by its value.  Very IDL.
#
img = read_raw(infile, camera, fibermapfile=fibermap, fill_header=None)

INFO:raw.py:114:read_raw: will add header keywords from hdus [0]
INFO:raw.py:136:read_raw: iotime 0.427 sec to read desi-00084523.fits.fz at 2021-12-16T09:42:39.594400
INFO:preproc.py:379:get_calibration_image: Using BIAS /global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/ccd/bias-sm4-r0-20210130.fits.gz
INFO:preproc.py:549:preproc: Use exptime = 677.6638 sec to compute the dark current
INFO:preproc.py:553:preproc: Using DARK model from /global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/ccd/dark-sm4-r0-20210130.fits.gz
INFO:preproc.py:1064:read_dark: Exposure time dependent dark
INFO:preproc.py:1096:read_dark: Interpolate between 600.0 and 900.0
INFO:preproc.py:558:preproc: dark is trimmed
INFO:preproc.py:582:preproc: subtracting bias
INFO:preproc.py:379:get_calibration_image: Using MASK /global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/ccd/pixmask-sm4-r-20201014.fits.gz
INFO:preproc.py:614:preproc: Using GAINA=1.655 from calibration data
INFO:preproc.py:628:preproc: Us

In [11]:
img

In [12]:
dir(img)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'camera',
 'fibermap',
 'ivar',
 'mask',
 'meta',
 'pix',
 'readnoise']

In [13]:
img.camera

'r0'

In [14]:
# img.fibermap is an afterthought added by desispec.io.read_raw().  It is not actually defined in desispec.image.Image.
img.fibermap

<Table length=500>
     TARGETID      PETAL_LOC DEVICE_LOC ...     FIBER_DEC      EXPTIME 
      int64          int16     int32    ...      float64       float64 
------------------ --------- ---------- ... ------------------ --------
 39627818581100303         0        311 ... 1.3157564374777024 677.6638
 39627818581103159         0        272 ... 1.3584159298852077 677.6638
 39627824625091229         0        252 ... 1.3836304426315482 677.6638
 39627824625094434         0        156 ... 1.5916925926170828 677.6638
 39627824629285168         0        198 ... 1.4486644803918198 677.6638
616088576924320374         0        204 ... 1.5093072232870037 677.6638
 39627824625092508         0        233 ... 1.4071508757064939 677.6638
 39627824625092423         0        172 ... 1.5338696770657358 677.6638
 39627818581101869         0        310 ... 1.2972467829267973 677.6638
 39627818581103277         0        290 ...   1.32787223267874 677.6638
               ...       ...        ... ...                ...      ...
 39627812549689827         0        486 ... 0.9255724630654427 677.6638
 39627812545498872         0        489 ... 0.9401617204802246 677.6638
616088564853113996         0        336 ... 1.1199735976626444 677.6638
 39627818589490512         0        260 ... 1.2615596921446475 677.6638
 39627818589489790         0        298 ... 1.2234514263295724 677.6638
 39627812545497323         0        507 ... 0.9059444599145766 677.6638
 39627812545499091         0        505 ... 0.9028496349995064 677.6638
 39627812545500400         0        503 ... 0.8996864331704878 677.6638
616088564853113966         0        357 ... 1.1141479832154713 677.6638
 39627812549690466         0        467 ... 0.9246703416262075 677.6638

In [15]:
img.fibermap.meta

OrderedDict([('TILEID', 276),
             ('TILERA', 218.163),
             ('TILEDEC', 2.47),
             ('FIELDROT', -0.0775474139512878),
             ('FA_PLAN', '2022-07-01T00:00:00.000'),
             ('FA_HA', 0.0),
             ('FA_RUN', '2021-03-17T23:20:01'),
             ('REQRA', 218.163),
             ('REQDEC', 2.47),
             ('FIELDNUM', 0),
             ('FA_VER', '2.2.0.dev2811'),
             ('FA_SURV', 'sv3'),
             ('DEPNAM00', 'python'),
             ('DEPVER00', '3.8.3'),
             ('DEPNAM01', 'numpy'),
             ('DEPVER01', '1.19.1'),
             ('DEPNAM02', 'matplotlib'),
             ('DEPVER02', '3.2.1'),
             ('DEPNAM03', 'astropy'),
             ('DEPVER03', '4.0.1.post1'),
             ('DEPNAM04', 'fitsio'),
             ('DEPVER04', '1.1.2'),
             ('DEPNAM05', 'desiutil'),
             ('DEPVER05', '3.2.1.dev916'),
             ('DEPNAM06', 'desimodel'),
             ('DEPVER06', '0.14.2'),
             ('DEPNAM0

In [16]:
img.mask

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint32)

In [17]:
img.meta

XTENSION= 'IMAGE   '           / binary table extension                         
BITPIX  =                   16 / data type of original image                    
NAXIS   =                    2 / dimension of original image                    
NAXIS1  =                 4256 / length of original image axis                  
NAXIS2  =                 4194 / length of original image axis                  
PCOUNT  =                    0 / size of special data area                      
GCOUNT  =                    1 / one data group (required keyword)              
EXTNAME = 'R0      '                                                            
EXPID   =                84523 / Exposure number                                
EXPFRAME=                    0 / Frame number                                   
FRAMES  =                      / Number of Frames in Archive                    
TILEID  =                  276 / DESI Tile ID                                   
FIBASSGN= '/data/tiles/SVN_t

In [18]:
img.pix

array([[ 2.11045704,  7.7448423 ,  2.45832112, ..., -2.46259993,
         4.33090229,  0.81134893],
       [ 3.06482252, -1.19552567,  2.32953787, ...,  0.65533684,
        -1.51177953,  2.45149875],
       [-1.39024539, -3.88754519,  0.22077565, ...,  2.70910487,
         0.31144919, -0.69671975],
       ...,
       [ 0.8307081 ,  0.35159399, -0.35699354, ...,  0.77241583,
         3.20506193, -2.09644644],
       [-1.3964215 ,  3.18523855,  2.19562814, ...,  1.84505351,
         3.32962628,  4.62337519],
       [ 6.9906753 ,  4.72882627,  3.5371139 , ...,  3.07116543,
         9.61322638,  5.00169688]])

In [19]:
img.readnoise

array([[2.86657181, 2.94223282, 2.8358455 , ..., 3.47028308, 3.21594366,
        2.83663923],
       [2.79307014, 2.81072278, 2.81072278, ..., 2.89963679, 2.86645762,
        2.78750411],
       [2.79307014, 2.79307014, 2.84417042, ..., 2.76837379, 2.79131444,
        2.66269612],
       ...,
       [2.81401545, 2.86182709, 2.8672465 , ..., 2.54615253, 2.48192751,
        2.56720384],
       [2.93978571, 3.03069016, 2.98936878, ..., 2.59638896, 2.77669251,
        2.71792065],
       [3.15857291, 3.20477276, 3.24683539, ..., 2.77669251, 2.86070795,
        2.81901323]])